README.md

Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. You have a descriptive commit message with a short title (first line).
c. You have only one commit (if not, squash them into one commit).
d. `python3 -m unittest tests` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to your PR.
b. Describe your changes.
c. Put `closes #XXXX` in your comment to auto-close …

Removed duplicated `transaction_id` argument.

---

lago_python_client/version.py

misc: Version 0.2.0

---

README.md
lago_python_client/clients/invoice_client.py
lago_python_client/models/invoice.py
tests/test_invoice_client.py

- Add invoice download endpoint support

feat: add invoice download

---

README.md
lago_python_client/models/plan.py

Remove Plan Charges amount_currency that will be removed on the API

feat: Remove Plan Charge Currency

---

.github/workflows/ci.yml
.github/workflows/pypi-push.yml
README.md
lago_python_client/clients/base_client.py
setup.cfg

Reverts getlago/lago-python-client#55

Revert "Customize LagoApiError"

---

lago_python_client/client.py
lago_python_client/clients/base_client.py
lago_python_client/clients/group_client.py
lago_python_client/clients/wallet_transaction_client.py

Refactor None usage
Motivation:
1. Minimise of `None` usage (optional reading: https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/)
2. Fix several `mypy` errors:
```
lago_python_client/client.py:24: error: Incompatible default for argument "api_key" (default has type "None", argument has type "str")  [assignment]
lago_python_client/client.py:24: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
lago_python_client/client.py:24: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
lago_python_client/client.py:24: error: Incompatible default for argument "api_url" (default has type "None", argument has type "str")  [assignment] …
```

Refactor None usage

---

lago_python_client/services/json.py
tests/test_json_services.py

Add json services

---

lago_python_client/clients/add_on_client.py
lago_python_client/clients/applied_add_on_client.py
lago_python_client/clients/applied_coupon_client.py
lago_python_client/clients/base_client.py
lago_python_client/clients/billable_metric_client.py
lago_python_client/clients/coupon_client.py
lago_python_client/clients/credit_note_client.py
lago_python_client/clients/customer_client.py
lago_python_client/clients/event_client.py
lago_python_client/clients/fee_client.py
lago_python_client/clients/group_client.py
lago_python_client/clients/invoice_client.py
lago_python_client/clients/organization_client.py
lago_python_client/clients/plan_client.py
lago_python_client/clients/subscription_client.py
lago_python_client/clients/wallet_client.py
lago_python_client/clients/wallet_transaction_client.py
lago_python_client/clients/webhook_client.py
lago_python_client/functools_ext.py
lago_python_client/services/request.py
lago_python_client/services/response.py
tests/test_response_services.py

Related issues: #91
- Add 4 services (with tests):
- - `prepare_object_response`
- - `prepare_index_response`
- - `prepare_create_response`

[Refactor] Add prepare response services (Part 1)

---

lago_python_client/models/__init__.py
lago_python_client/models/add_on.py
lago_python_client/models/applied_add_on.py
lago_python_client/models/applied_coupon.py
lago_python_client/models/billable_metric.py
lago_python_client/models/charge.py
lago_python_client/models/coupon.py
lago_python_client/models/credit.py
lago_python_client/models/credit_note.py
lago_python_client/models/customer.py
lago_python_client/models/customer_usage.py
lago_python_client/models/event.py
lago_python_client/models/fee.py
lago_python_client/models/group.py
lago_python_client/models/invoice.py
lago_python_client/models/invoice_item.py
lago_python_client/models/organization.py
lago_python_client/models/plan.py
lago_python_client/models/subscription.py
lago_python_client/models/wallet.py
lago_python_client/models/wallet_transaction.py
tests/test_add_on_client.py
tests/test_credit_note_client.py

Fix mypy errors in models, reorder imports (Part 4)

---

lago_python_client/clients/add_on_client.py
lago_python_client/clients/applied_add_on_client.py
lago_python_client/clients/applied_coupon_client.py
lago_python_client/clients/billable_metric_client.py
lago_python_client/clients/coupon_client.py
lago_python_client/clients/credit_note_client.py
lago_python_client/clients/customer_client.py
lago_python_client/clients/event_client.py
lago_python_client/clients/fee_client.py
lago_python_client/clients/group_client.py
lago_python_client/clients/invoice_client.py
lago_python_client/clients/organization_client.py
lago_python_client/clients/plan_client.py
lago_python_client/clients/subscription_client.py
lago_python_client/clients/wallet_client.py
lago_python_client/clients/wallet_transaction_client.py
lago_python_client/clients/webhook_client.py
lago_python_client/mixins.py
lago_python_client/services/response.py

Improve typing support (Generics) and refactor `*Client` requests code (Part 5)

---

lago_python_client/clients/applied_coupon_client.py
lago_python_client/clients/base_client.py
lago_python_client/clients/credit_note_client.py
lago_python_client/clients/customer_client.py
lago_python_client/clients/event_client.py
lago_python_client/clients/group_client.py
lago_python_client/clients/invoice_client.py
lago_python_client/clients/wallet_transaction_client.py
lago_python_client/clients/webhook_client.py
lago_python_client/mixins.py
lago_python_client/services/request.py
tests/test_request_services.py

Fix #90 - [Refactor] Add make_headers service (Part 7)

---

lago_python_client/clients/fee_client.py
lago_python_client/clients/wallet_transaction_client.py
lago_python_client/functools_ext.py
lago_python_client/models/customer_usage.py
lago_python_client/services/json.py
lago_python_client/services/response.py
tests/test_response_services.py
tests/test_subscription_client.py
tests/test_wallet_client.py
tests/test_wallet_transaction_client.py
tests/test_webhook_client.py

#114 Check all PR comments for (Part 1) - (Part 8) and make requested changes

---

lago_python_client/clients/applied_add_on_client.py
lago_python_client/clients/applied_coupon_client.py
lago_python_client/clients/credit_note_client.py
lago_python_client/clients/customer_client.py
lago_python_client/clients/event_client.py
lago_python_client/clients/fee_client.py
lago_python_client/clients/group_client.py
lago_python_client/clients/invoice_client.py
lago_python_client/clients/organization_client.py
lago_python_client/clients/subscription_client.py
lago_python_client/clients/wallet_transaction_client.py
lago_python_client/clients/webhook_client.py

Fix #88 Fix #114 Remove unused *Client methods

---

lago_python_client/base_model.py
lago_python_client/models/add_on.py
lago_python_client/models/applied_add_on.py
lago_python_client/models/applied_coupon.py
lago_python_client/models/billable_metric.py
lago_python_client/models/charge.py
lago_python_client/models/coupon.py
lago_python_client/models/credit.py
lago_python_client/models/credit_note.py
lago_python_client/models/customer.py
lago_python_client/models/customer_usage.py
lago_python_client/models/event.py
lago_python_client/models/fee.py
lago_python_client/models/group.py
lago_python_client/models/invoice.py
lago_python_client/models/invoice_item.py
lago_python_client/models/organization.py
lago_python_client/models/plan.py
lago_python_client/models/subscription.py
lago_python_client/models/wallet.py
lago_python_client/models/wallet_transaction.py

Fix #85 - Output Pydantic models should be frozen (hashable)

---

CONTRIBUTING.md

Update the contribution guide to improve the contribution experience:
- Fix links to community slack
- Fix link to feature request tool
- Fix issues and pull request labels

misc: Update and fix contribution guide

---

.github/ISSUE_TEMPLATE/config.yml

This PR fixes the link to the community forum

misc: Update link to community forum

---

lago_python_client/events/clients.py
lago_python_client/mixins.py
lago_python_client/services/json.py
lago_python_client/services/request.py
lago_python_client/services/response.py
lago_python_client/wallets/clients.py
setup.cfg
tests/test_add_on_client.py
tests/test_applied_add_on_client.py
tests/test_applied_coupon_client.py
tests/test_billable_metric_client.py
tests/test_coupon_client.py
tests/test_credit_note_client.py
tests/test_customer_client.py
tests/test_event_client.py
tests/test_fee_client.py
tests/test_group_client.py
tests/test_invoice_client.py
tests/test_json_services.py
tests/test_organization_client.py
tests/test_plan_client.py
tests/test_request_services.py
tests/test_response_services.py
tests/test_subscription_client.py
tests/test_wallet_client.py
tests/test_wallet_transaction_client.py
tests/test_webhook_client.py

Fix #94 - Replace requests to httpx. Change `to_json` service to return bytes

---

setup.cfg

(I worry about next `classes` update. Better to pin it now.)

Pin dependencies

---

setup.cfg

>classifiers =
>>     Development Status :: 4 - Beta
>>     Intended Audience :: Developers
>>     License :: OSI Approved :: MIT License
>>     Operating System :: OS Independent
>>     Programming Language :: Python :: 3
>>     Programming Language :: Python :: 3 :: Only
>>     Programming Language :: Python :: 3.7
>>     Programming Language :: Python :: 3.8
>>     Programming Language :: Python :: 3.9
>>     Programming Language :: Python :: 3.10
>>     Programming Language :: Python :: 3.11
>>     Topic :: Software Development

Add more classifiers

---

lago_python_client/models/coupon.py
tests/fixtures/coupon.json
tests/test_coupon_client.py

This PR adds the coupon's description attribute now available

feat: add description field to coupons

---

lago_python_client/models/customer.py
tests/fixtures/customer.json
tests/test_customer_client.py

Add provider_payment_methods field to the CustomerBillingConfiguration model
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. You have a descriptive commit message with a short title (first line).
c. You have only one commit (if not, squash them into one commit).
d. `python3 -m pytest tests` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to your PR.
b. …

feat: add provider_payment_methods to billing configurations

---

lago_python_client/customers/clients.py

- Add `checkout_url` endpoint for `customers`

feat(customers): Add checkout_url endpoint

---

lago_python_client/models/customer.py
tests/fixtures/customer.json
tests/fixtures/invoice.json
tests/fixtures/one_off_invoice.json
tests/test_customer_client.py

Add payment_provider_code to customer's billing configuration.

feat(psp-accounts): Add payment_provider_code

---

lago_python_client/invoices/clients.py
tests/fixtures/payment_url.json
tests/test_invoice_client.py

This PR adds support for generating invoice payment url

feat (invoice-payment-url): add support for invoice payment url

---

lago_python_client/models/__init__.py
lago_python_client/models/customer.py
tests/fixtures/customer.json
tests/test_customer_client.py

Change `integration_customer` param to `integration_customers`

misc: Change integration_customer param to integration_customers

---

lago_python_client/models/__init__.py
lago_python_client/models/customer.py
tests/fixtures/customer.json
tests/test_customer_client.py

This PR updates integration customer definition based on the new logic for removing integration customer

feat(integration-customers): update integration customer definition

---

lago_python_client/version.py

Bumps version to 1.9.1.
- Fixes #263

misc(version) - bump version to 1.9.1

---

lago_python_client/base_client.py
lago_python_client/client.py
lago_python_client/events/clients.py
tests/test_event_client.py

This PR adds the support for the future ingest API for events on Lago US cluster.
Support for EU cluster and self-hosted will come later

feat(event): Add support for ingest API

---

lago_python_client/models/subscription.py
tests/fixtures/one_off_invoice.json
tests/fixtures/pending_subscription.json
tests/fixtures/subscription.json

The goal of this PR is to add current billing period dates at the subscription level.

feat: Add current billing period dates

---

lago_python_client/models/fee.py
tests/fixtures/fee.json
tests/fixtures/fees.json
tests/fixtures/invoice.json

Related to https://github.com/getlago/lago-api/pull/2710
Exposes the new `fees#charge_id` field

feat(fee): Expose charge_id

---

lago_python_client/models/customer.py
lago_python_client/models/invoice.py
tests/test_customer_client.py

Add invoice_custom_sections related updates

Feat(invoice_custom_sections): updated python client with invoice_custom_sections

---

lago_python_client/client.py
lago_python_client/models/__init__.py
lago_python_client/models/invoice.py
lago_python_client/models/payment.py
lago_python_client/payments/clients.py
tests/fixtures/invoice.json
tests/fixtures/invoice_index.json
tests/fixtures/one_off_invoice.json
tests/fixtures/payment.json
tests/fixtures/payment_index.json
tests/fixtures/payment_request_index.json
tests/test_payment_client.py

feat(manual-payments): Add manual payments

---

lago_python_client/models/wallet.py
lago_python_client/models/wallet_transaction.py
tests/fixtures/wallet_transaction.json
tests/test_wallet_transaction_client.py

Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. You have a descriptive commit message with a short title (first line).
c. You have only one commit (if not, squash them into one commit).
d. `python3 -m pytest tests` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to your PR.
b. Describe your changes.
c. Put `closes #XXXX` in your comment to auto-close …

feat: Add expired at transaction rules

---

lago_python_client/models/subscription.py

This PR adds termination / upgrade / downgrade support for invoice preview feature

feat (invoice-preview): add support for invoice preview termination and upgrade / downgrade

---

lago_python_client/client.py
lago_python_client/models/__init__.py
lago_python_client/models/payment_receipt.py
lago_python_client/payment_receipts/clients.py
tests/fixtures/payment_receipt.json
tests/fixtures/payment_receipt_index.json
tests/test_payment_receipt_client.py

This PR adds payment receipts endpoints

feat(payment-receipts): Add payment receipts

---

.gitignore
lago_python_client/invoices/clients.py
tests/test_invoice_client.py

Thist PR add the missing `Invoice#void` action

feat(invoice): Add missing void action

---

lago_python_client/payment_requests/clients.py
tests/test_payment_request_client.py

Add `GET /api/v1/payment_requests/:id` endpoint

feat(api): Add GET payment_request endpoint
