getlago/lago-python-client

README.md, lago_python_client/clients/base_client.py, lago_python_client/clients/event_client.py, lago_python_client/models/event.py, tests/fixtures/event.json, tests/test_event_client.py
Following recent introduction of the event `find` route on lago api (https://github.com/getlago/lago-api/pull/269), this PR aims to replicate the update of the ruby client (https://github.com/getlago/lago-ruby-client/pull/16)
=> feat: Add route to find an event by it's transaction id

README.md, lago_python_client/models/customer.py
Add a new sync flag in customer[billing_configuration] in order to allow synchronous creation of the stripe customer. It will return the stripe customer ID immediately rather by waiting for the webhook
=> feat: synchronous stripe customer creation

README.md, lago_python_client/clients/customer_client.py, lago_python_client/models/__init__.py, lago_python_client/models/customer_usage.py, tests/fixtures/customer_usage.json, tests/test_customer_client.py
Add new `GET /api/v1/customers/:customer_id/current_usage` route
Related to:
- https://github.com/getlago/lago-api/pull/322
- https://github.com/getlago/lago-docs/pull/15
=> feat: Add new customer current usage route

lago_python_client/models/plan.py, lago_python_client/version.py, tests/fixtures/graduated_plan.json, tests/test_plan_client.py
** Context **
Plan Charge type is wrong when graduated or package, it generates validation error
** Changes ** 
Adapt the Plan Charge type to support either `dict` or `list`
=> fix: plan with graduated charge type

README.md, lago_python_client/clients/customer_client.py, lago_python_client/models/applied_add_on.py, lago_python_client/models/applied_coupon.py, lago_python_client/models/customer.py, lago_python_client/models/event.py, lago_python_client/models/subscription.py, tests/fixtures/applied_add_on.json, tests/fixtures/applied_coupon.json, tests/fixtures/customer.json, tests/fixtures/event.json, tests/fixtures/subscription.json, tests/fixtures/subscription_index.json, tests/test_applied_add_on_client.py, tests/test_applied_coupon_client.py, tests/test_customer_client.py, tests/test_event_client.py, tests/test_subscription_client.py
We want to clarify the difference between lago ids and external ids.
Today, we have `customer_id` on customers and `subscription_id|unique_id` on subscriptions.
On the API, the goal is to use external_ids:
- `external_id` or `external_customer_id` for customer
- `external_id` or `external_subscription_id` for subscription
The goal of this PR is to:
- rename `customer_id` to `external_id` on customers
- rename `subscription_id` to `external_id` on subscriptions
- remove `unique_id` from subscriptions
=> misc: Use external_id instead of customer_id and subscription_id

lago_python_client/models/subscription.py, tests/fixtures/subscription.json
This PR is adding support for the following attributes on Subscription:
- `previous_plan_code`
- `next_plan_code`
- `downgrade_plan_date`
=> feat: Add previous and next attributes on Subscription

lago_python_client/models/subscription.py, tests/test_subscription_client.py
This PR adds support for `subscription_date` param when creating or updating subscription
=> feat (subscriptions): add support for subscription date param

lago_python_client/models/plan.py, tests/fixtures/graduated_plan.json, tests/test_plan_client.py
In order to be consistent between all charge models, we want to store `properties` by using the same type.
The goal of this MR is to update `properties` from `array` to `hash` for graduated charges.
=> misc: Use graduated ranges as hash

lago_python_client/models/__init__.py, lago_python_client/models/billable_metric.py, tests/fixtures/billable_metric.json, tests/fixtures/billable_metric_index.json, tests/test_billable_metric_client.py
👉  https://github.com/getlago/lago/issues/32
We want to be able to price differently billable metrics according to several dimensions (groups).
For example, creating a `storage` pricing based on the `region of the server` and the `cloud provider` used.
This PR adds `group` on `billable_metric`.
=> feat(groups): Add group on billable metric

lago_python_client/client.py, lago_python_client/clients/group_client.py, lago_python_client/models/group.py, lago_python_client/models/plan.py, tests/__init__.py, tests/fixtures/group_index.json, tests/fixtures/plan_index.json, tests/test_group_client.py, tests/test_plan_client.py
👉  https://github.com/getlago/lago/issues/32
We want to be able to price differently billable metrics according to several dimensions (groups).
For example, creating a `storage` pricing based on the `region of the server` and the `cloud provider` used.
This PR adds documentation for:
- `group_properties` on `charge` creation
- `GET billables_metrics/:code/groups` endpoint
=> feat(groups): Add group_properties on charge and groups endpoint

lago_python_client/models/__init__.py, lago_python_client/models/customer.py, lago_python_client/models/organization.py, tests/fixtures/customer.json, tests/fixtures/organization.json, tests/test_customer_client.py, tests/test_organization_client.py
👉  https://github.com/getlago/lago/issues/99
The goal of this PR is to move fields related to Billing or Invoice into `billing_configuration`.
For customer: `vat_rate`.
For organization: `invoice_footer`, `vat_rate`.
=> misc: Move fields to billing configuration

lago_python_client/client.py, lago_python_client/clients/__init__.py, lago_python_client/clients/credit_note_client.py, lago_python_client/models/__init__.py, lago_python_client/models/credit_note.py, lago_python_client/models/invoice.py, lago_python_client/models/subscription.py, tests/__init__.py, tests/fixtures/credit_note.json, tests/fixtures/credit_note_index.json, tests/fixtures/invoice.json, tests/test_credit_note_client.py
👉  https://github.com/getlago/lago/issues/59
The objective of this feature is to introduce a new concept of credit notes.
The main reason behind this need is to handle the following case:
- If an overdue has been paid because a customer passes from a yearly plan to a monthly plan (`in_advance`), we charge the customer as if the remainder does not exist.
This PR adds the credit note API clients
Related to https://github.com/getlago/lago-api/pull/505
=> feat(credit_notes): Add Credit note API client

lago_python_client/models/coupon.py, lago_python_client/models/customer.py, lago_python_client/models/customer_usage.py, lago_python_client/models/organization.py, lago_python_client/models/wallet.py, tests/fixtures/coupon.json, tests/fixtures/customer.json, tests/fixtures/customer_usage.json, tests/fixtures/invoice.json, tests/fixtures/organization.json, tests/fixtures/wallet.json, tests/test_coupon_client.py, tests/test_customer_client.py
👉  https://github.com/getlago/lago/issues/61
It’s impossible to bill a customer following its own timezone.
Lago ingests events, creates subscription boundaries and trigger invoices on a UTC timezone, which is the same for everyone.
This feature adds the possibility to choose the timezone an organization or a customer should be billed in.
This PR adds:
- Support for timezone at customer level
- Support for timezone at organization level
- Replace `expiration_date` by `expiration_at` on coupons
- Replace `expiration_date` by `expiration_at` on wallets
- Replace `from_date` and `to_date` by `from_datetime` and `to_datetime` on customer usage
=> feat(timezones): Update clients to support customer timezones

lago_python_client/models/wallet.py
- `currency` is actually not defined for `wallets`
=> fix(wallets): add Currency in wallet model

.github/workflows/ci.yml, .github/workflows/pypi-push.yml, README.md, lago_python_client/clients/base_client.py, setup.cfg
PR is based on Slack discussion here: https://lago-community.slack.com/archives/C03MCH55EL8/p1672173754139359
=> Customize LagoApiError

lago_python_client/clients/webhook_client.py, tests/fixtures/webhook.json, tests/test_webhook_client.py
`/api/v1/webhooks/public_key` endpoint changed reponse to json format:
{'webhook': {'public_key': 'public key encoded'}}
This PR adds support for mentioned changes
=> feat (webhooks): add support for webhook public key changes

lago_python_client/models/billable_metric.py, tests/fixtures/billable_metric.json, tests/fixtures/billable_metric_index.json
👉  https://github.com/getlago/lago/issues/179
As a user, I want to be able to delete a billable metric that is linked to a subscription in case of a change of pricing (e.g. we no longer charge customers based on the number of API calls).
Once deleted, the corresponding charges will be removed from the plans and from all draft invoices.
Deleted metrics will still be included in past invoices (i.e. finalized invoices).
The goal of this PR is to add on the billable metric response:
- `activeSubscriptionsCount`
- `draftInvoicesCount`
These fields are used to know the impact of deleting billable metric.
=> feat(delete_bm): Update response and tests for billable metric deletion

tests/test_customer_client.py
Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete customers.
The goal of this feature is to be able to soft-delete a customer linked to an active or terminated subscription.
This PR adds some tests for the new Customer destroy route added in https://github.com/getlago/lago-api/pull/779
=> feat(delete_customer): Add tests for the customer destroy route

lago_python_client/clients/applied_coupon_client.py, lago_python_client/clients/base_client.py, lago_python_client/clients/credit_note_client.py, lago_python_client/clients/customer_client.py, lago_python_client/clients/event_client.py, lago_python_client/clients/group_client.py, lago_python_client/clients/invoice_client.py, lago_python_client/clients/wallet_transaction_client.py, lago_python_client/clients/webhook_client.py, lago_python_client/exceptions.py, lago_python_client/services/json.py, lago_python_client/services/response.py, tests/test_add_on_client.py, tests/test_applied_add_on_client.py, tests/test_applied_coupon_client.py, tests/test_billable_metric_client.py, tests/test_coupon_client.py, tests/test_credit_note_client.py, tests/test_customer_client.py, tests/test_event_client.py, tests/test_invoice_client.py, tests/test_json_services.py, tests/test_organization_client.py, tests/test_plan_client.py, tests/test_response_services.py, tests/test_subscription_client.py, tests/test_wallet_client.py, tests/test_wallet_transaction_client.py, tests/test_webhook_client.py
Main commit in this PR is here: https://github.com/getlago/lago-python-client/pull/79/commits/3449d040d5b0d89b4b8cbf8487f736eb4af51a17
First two commits are just small refactoring and two last commits small test compatibility fixes
=> Fix #73 Raise `LagoApiError` with `500` status code around `invalid json` or `empty data` cases

lago_python_client/client.py, lago_python_client/functools_ext.py, tests/test_client.py, tests/test_functools_ext.py
Related issue: #86 
P.S. I suggest to make `client.collection.method()` default in docs. `()` usually means some action (and usually start from verb, not noun).
`.get_collection()` and `.collection` looks good but `.collection()` and `.get_collection` are not very beautiful.
(IMHO, may be it's just my perfectionism)
P.P.S. Also check Ruby client. Looks like it has similar problem (lack of cache)
=> Fix #86 Cache `*Client` instances

lago_python_client/models/__init__.py, lago_python_client/models/billable_metric.py, lago_python_client/models/charge.py, lago_python_client/models/plan.py, tests/fixtures/billable_metric.json, tests/fixtures/billable_metric_index.json, tests/fixtures/plan.json, tests/fixtures/plan_index.json
Plans edition has some issue if you update some properties of a billable metric, especially if you change groups definition or aggregation type :
"After the billable metric edition, new dimensions are created with new group_id that do not match the ones in the plans already defined"
This PR exposes a new `plans_count` field in the `BillableMetric` response type to let the API users know if the BM is editable.
Related to https://github.com/getlago/lago-api/pull/914
=> feat(bm): Expose count of attached plans

.github/workflows/ci.yml, .github/workflows/pypi-push.yml, setup.cfg
You can keep working as usual and even use unittest tests if you like them more than pytest. Test refactoring is not required.
But if not, check pytest docs https://docs.pytest.org/en/7.2.x/ And may be you will find something useful for you.
For example, may be you will use `assert` instead of `self.assertEqual` and so on...
Related issue: #97
=> Fix #97 - [Tests] Use pytest instead of unittests

lago_python_client/clients/add_on_client.py, lago_python_client/clients/applied_add_on_client.py, lago_python_client/clients/applied_coupon_client.py, lago_python_client/clients/base_client.py, lago_python_client/clients/billable_metric_client.py, lago_python_client/clients/coupon_client.py, lago_python_client/clients/credit_note_client.py, lago_python_client/clients/customer_client.py, lago_python_client/clients/event_client.py, lago_python_client/clients/group_client.py, lago_python_client/clients/invoice_client.py, lago_python_client/clients/organization_client.py, lago_python_client/clients/plan_client.py, lago_python_client/clients/subscription_client.py, lago_python_client/clients/wallet_client.py, lago_python_client/clients/wallet_transaction_client.py, lago_python_client/clients/webhook_client.py, lago_python_client/services/request.py, tests/test_request_services.py
- - `make_url(*, origin: str, path_parts: Sequence[str], query_pairs: Dict[str, str] = {}) -> str
Return url.`
- - we call `make_url` service instead of repeating the same url construction code here and there (https://en.wikipedia.org/wiki/Single-responsibility_principle)
- - we make `*Client` methods looks closer to pipelines (which call services step by step and do nothing else https://returns.readthedocs.io/en/latest/pages/pipeline.html) 
Main commit for review is here: https://github.com/getlago/lago-python-client/pull/83/commits/434f59805a4cf20e9c71eef8e664b577683e5f75
URI scheme description: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
```
userinfo       host      port
┌──┴───┐ ┌──────┴──────┐ ┌┴┐
https://john.doe@www.example.com:123/forum/questions/?tag=networking&order …
```
=> Add `make_url` service

README.md, lago_python_client/clients/applied_coupon_client.py, lago_python_client/clients/base_client.py, lago_python_client/clients/credit_note_client.py, lago_python_client/clients/customer_client.py, lago_python_client/clients/event_client.py, lago_python_client/clients/group_client.py, lago_python_client/clients/invoice_client.py, lago_python_client/clients/wallet_transaction_client.py, lago_python_client/clients/webhook_client.py, lago_python_client/functools_ext.py, lago_python_client/services/json.py, lago_python_client/services/response.py, setup.cfg, tests/test_response_services.py
Related issues: #91 
- Add `get_response_data` service (with tests)
- Update `README.md`
- Install `typeguard` (https://typeguard.readthedocs.io/en/latest/index.html)
- Install (dev dependency) `mypy` (https://www.mypy-lang.org/)
- Use `typeguard` to check types in existed prepare response services
=> Fix #91 - [Refactor] Add prepare response services (Part 2)

lago_python_client/clients/event_client.py, tests/fixtures/fees.json, tests/test_event_client.py
👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds the new `POST api/v1/events/estimate_fees` route
Related to https://github.com/getlago/lago-api/pull/923
=> feat(instant_charge): Add API route to estimate instant fees amount

README.md, lago_python_client/clients/fee_client.py, lago_python_client/models/__init__.py, lago_python_client/models/fee.py, lago_python_client/models/invoice_item.py
👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds:
- Definition for `GET /api/v1/fees`
- Definition for `PUT /api/v1/fees/:id`
- Add new fields definition to fees:
- lago_invoice_id
- external_subscription_id
- payment_status
- created_at
- succeeded_at
- failed_at
- refunded_at
- …
=> feat(instant_charge): Expose fees updapte and get all routes

lago_python_client/functools_ext.py
We show here that `client.tag.operation()` is preferred way over `client.tag().operation()`.
```
➜  lago-python-client git:(main) python3
Python 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import this
The Zen of Python, by Tim Peters
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and …
```
=> Add PendingDeprecation warnings if someone uses `client.tag().operation()` instead of `client.tag.operation()`

tests/test_add_on_client.py, tests/test_applied_add_on_client.py, tests/test_applied_coupon_client.py, tests/test_billable_metric_client.py, tests/test_coupon_client.py, tests/test_credit_note_client.py, tests/test_customer_client.py, tests/test_event_client.py, tests/test_fee_client.py, tests/test_functools_ext.py, tests/test_group_client.py, tests/test_invoice_client.py, tests/test_organization_client.py, tests/test_plan_client.py, tests/test_subscription_client.py, tests/test_wallet_client.py, tests/test_wallet_transaction_client.py, tests/test_webhook_client.py
Remove `client.<tag>` braces in tests to hide pytest warnings (except one test where it's required to test compatibility)...
=> Fix pytest warnings

lago_python_client/models/invoice.py, tests/fixtures/invoice.json, tests/fixtures/invoice_index.json
Related issue:
- #145 
https://doc.getlago.com/docs/api/invoices/invoice-object
=> Fix #145 - Add `number` field to `InvoiceResponse` model

lago_python_client/client.py, lago_python_client/models/__init__.py, lago_python_client/models/tax_rate.py, lago_python_client/tax_rates/clients.py, tests/fixtures/tax_rate.json, tests/fixtures/tax_rate_index.json, tests/test_tax_rate_client.py
👉  [https://getlago.canny.io/feature-requests/p/create-several-tax-rates](https://getlago.canny.io/feature-requests/p/create-several-tax-rates)
Currently, tax can be set individually either on the customer or the organization level. However, it’s not possible to define a global tax tag that can be reusable everywhere.
The goal of this PR is to be able to add the TaxRate resource.
=> feat(tax_rates): Add tax rate resource

lago_python_client/models/charge.py, tests/test_plan_client.py
This PR is a fix for the `charge#group_properties` definition.
In Lago API and in openapi definition, this `group_properties` is defined as an array of object, while the current implementation in the client expects an object
=> fix(charge): Group propeties should be a list

lago_python_client/mixins.py, tests/fixtures/pending_subscription.json, tests/test_subscription_client.py
This PR adds 2 improvements
- You can now delete a pending subscription by passing a status=pending as query param
- You can now filter GET /subscriptions by passing an array of status as query param
=> feat(subscription) allow to pass status to index and delete

lago_python_client/models/applied_coupon.py
Applying coupons with percentage discount raises the error
```
pydantic.error_wrappers.ValidationError: 2 validation errors for AppliedCouponResponse 
amount_cents
none is not an allowed value (type=type_error.none.not_allowed)
amount_currency
none is not an allowed value (type=type_error.none.not_allowed)
```
=> fix: applying coupons with percentage discount

lago_python_client/models/coupon.py
Fetching coupons with percentage discount raise the error
```
pydantic.error_wrappers.ValidationError: 2 validation errors for CouponResponse 
amount_cents
none is not an allowed value (type=type_error.none.not_allowed)
amount_currency
none is not an allowed value (type=type_error.none.not_allowed)
```
=> fix: fetch coupons with percentage discount

lago_python_client/mixins.py
Add httpx timeout to request mixins (`create`, `destroy`, `find_all`, `find`, `update`)
Usage:
```
from httpx import Timeout
client = Client(api_key='__YOUR_API_KEY__')
client.invoices.find_all({'per_page': 2, 'page': 1}, timeout=Timeout(30))
```
Use case: 
Since there is no ability to exclude zero amount invoices when fetching, the number may be large for a particular date range. This causes a `ReadTimout` exception to occur when the request takes more than 5 seconds [which is the default for httpx](https://github.com/encode/httpx/blob/master/httpx/_config.py#L367)
=> feat: add httpx Timeout optional parameter

lago_python_client/models/invoice_item.py
`InvoiceItemResponse` model defines a field `lago_item_id` which is not returned on API. The correct field is `lago_id`
=> fix: correct field name from `lago_item_id` to `lago_id`

lago_python_client/subscriptions/clients.py, tests/test_subscription_client.py
We want to improve the way we are overriding a plan. Without working as a duplicate, by adding the logic for managing parent and children of plans.
The goal of this PR is to add the endpoint `GET /api/v1/subscriptions/:external_id`.
=> feat(override-plan): Ability to fetch a single subscription

lago_python_client/customers/clients.py, lago_python_client/models/customer_usage.py, tests/fixtures/customer_past_usage.json, tests/fixtures/customer_usage.json, tests/test_customer_client.py
Some of our users want to retrieve usage in the past. The main problem they are facing is that at the beginning of a new period, they cannot compute usage in third party systems, or see if everything went well as usage for the past period has been removed.
This PR adds a new route to fetch the past_usage for a customer/subscription.
=> feat(past_usage): Expose route to fetch customer past usage

lago_python_client/models/add_on.py, lago_python_client/models/charge.py, lago_python_client/models/fee.py, lago_python_client/models/invoice.py, lago_python_client/models/invoice_item.py, lago_python_client/models/plan.py, tests/fixtures/add_on.json, tests/fixtures/add_on_index.json, tests/fixtures/credit_note.json, tests/fixtures/customer_usage.json, tests/fixtures/fee.json, tests/fixtures/fees.json, tests/fixtures/graduated_plan.json, tests/fixtures/invoice.json, tests/fixtures/one_off_invoice.json, tests/fixtures/plan.json, tests/fixtures/plan_index.json, tests/test_add_on_client.py, tests/test_fee_client.py, tests/test_invoice_client.py, tests/test_plan_client.py
Add a custom name to display on invoice for subscription fee and charges
When generating an invoice, don't display the name of the plan or the name of the billable metrics to the customer.
=> feat(invoice_display_name): Add invoice display name

.gitignore, lago_python_client/credit_notes/clients.py, lago_python_client/models/__init__.py, lago_python_client/models/credit_note.py, tests/fixtures/credit_note_estimated.json, tests/test_credit_note_client.py
Add route for https://github.com/getlago/lago-api/pull/1412
=> feat(credit-note): Add estimate route before creation

lago_python_client/client.py, lago_python_client/gross_revenues/clients.py, lago_python_client/invoiced_usages/clients.py, lago_python_client/models/gross_revenue.py, lago_python_client/models/invoiced_usage.py, lago_python_client/models/mrr.py, lago_python_client/models/outstanding_invoice.py, lago_python_client/mrrs/clients.py, lago_python_client/outstanding_invoices/clients.py, tests/fixtures/gross_revenue_index.json, tests/fixtures/invoiced_usage_index.json, tests/fixtures/mrr_index.json, tests/fixtures/outstanding_invoice_index.json, tests/test_gross_revenue_client.py, tests/test_invoiced_usage_client.py, tests/test_mrr_client.py, tests/test_outstanding_invoices_client.py
=> feat(analytics): Add analytics resources

lago_python_client/models/customer_usage.py, lago_python_client/models/invoice_item.py, tests/fixtures/customer_usage.json, tests/fixtures/fee.json, tests/fixtures/fees.json, tests/fixtures/plan.json
Some customers have requested a way to group usage fees on an invoice using an event property. The same charge model properties should be applied to each group. The logic will only apply to `standard` charge model.
This PR adds all the new fields related to the feature
=> feat(grouped-by): Add new fields

lago_python_client/base_client.py, lago_python_client/base_model.py, lago_python_client/events/clients.py, lago_python_client/mixins.py, lago_python_client/models/add_on.py, lago_python_client/models/applied_coupon.py, lago_python_client/models/billable_metric.py, lago_python_client/models/charge.py, lago_python_client/models/coupon.py, lago_python_client/models/credit.py, lago_python_client/models/credit_note.py, lago_python_client/models/customer.py, lago_python_client/models/customer_usage.py, lago_python_client/models/event.py, lago_python_client/models/group.py, lago_python_client/models/invoice.py, lago_python_client/models/organization.py, lago_python_client/models/plan.py, lago_python_client/models/subscription.py, lago_python_client/models/tax.py, lago_python_client/models/wallet.py, lago_python_client/models/wallet_transaction.py, lago_python_client/models/webhook_endpoint.py, lago_python_client/services/response.py, lago_python_client/wallets/clients.py, lago_python_client/webhook_endpoints/clients.py, lago_python_client/webhooks/clients.py, setup.cfg, tests/test_response_services.py
As it stands, any project using `lago-python-client` can't upgrade to Pydantic V2 due to version constraints. Fortunately for us, Pydantic V2 ships with V1 to allow for incremental adoption, which allows us to support both V1 and V2 without fundamentally changing the package's code:
```python
try:
from pydantic.v1 import BaseModel 
except ImportError:
from pydantic import BaseModel
```
In addition to this, I changed all the `from pydantic import BaseModel` imports to pull from `base_model` instead.
Feature - non-breaking change
Used `pytest` to run the tests once for each version. To replicate:
1. Install the project's base dependencies (in a virtualenv ideally).
```bash
pip install -e .
```
2. Install Pydantic V1.
```bash
pip install pydantic==1.10
```
3. Run pytest.
```bash
pytest
``` …
=> feat: add support for Pydantic V2

lago_python_client/models/__init__.py, lago_python_client/models/minimum_commitment.py, lago_python_client/models/plan.py, tests/fixtures/plan.json, tests/fixtures/plan_index.json, tests/test_plan_client.py
👉  https://getlago.canny.io/feature-requests/p/set-minimum-spend-for-subscriptions
As a user, I want to define the minimum spend that applies to the customer's plan. Consider the following monthly plan:
- Subscription fee = $50 per month (in arrears);
- Usage-based charge = $10 per unit per month (in arrears); and
- Monthly minimum spend = $100.
If at the end of the month, the customer has consumed 3 units, their total invoice will be: $50 + 3 * $10 = $80 + $20 (true-up fee) = $100.
This PR adds minimum commitment to plan and plan overrides.
=> feat(minimum-commitment): Add minimum commitment

lago_python_client/models/invoice.py
Currently, we generate `sequential_id` upon invoice finalization. When the invoice is draft `sequential_id` could be nil.
We have to make this field optional in api response.
=> fix: mark sequential_id as optional

tests/fixtures/credit_note_index.json, tests/fixtures/wallet_index.json
The goal of this PR is to add:
- `items` to `CreditNotesController#index`
- `recurring_transaction_rules` to `WalletsController#index`
=> feat: Add recurring_transaction_rules and items to responses

lago_python_client/models/billable_metric.py, lago_python_client/models/charge.py, lago_python_client/models/customer_usage.py, lago_python_client/models/fee.py, lago_python_client/models/invoice_item.py, tests/fixtures/billable_metric.json, tests/fixtures/billable_metric_index.json, tests/fixtures/customer_past_usage.json, tests/fixtures/customer_usage.json, tests/fixtures/fee.json, tests/fixtures/fees.json, tests/fixtures/invoice.json, tests/fixtures/plan.json
Lago is not currently supporting more than 2 levels of event grouping (parent → children)
The goal of this feature is to allow more flexibility of event grouping by allowing an unlimited level of grouping and making it easier to define default charge properties for events based on their properties.
This PR is related to https://github.com/getlago/lago-openapi/pull/210
It adds the new filter fields in both input and output objects
=> feat(filter): Add filter fields

lago_python_client/models/wallet_transaction.py, tests/test_wallet_transaction_client.py
We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to create a voided wallet transaction.
=> feat(wallet): Add voided_credits to WalletTransaction

lago_python_client/models/wallet.py, tests/fixtures/wallet.json, tests/fixtures/wallet_index.json, tests/test_wallet_client.py
After the release of real-time wallet version 1, some customers have expressed concerns about odd or missing behaviors.
The goal of this PR is to rename `Wallet#rule_type` into `Wallet#trigger`.
=> feat(wallet): Rename wallet rule_type into trigger

lago_python_client/models/__init__.py, lago_python_client/models/customer.py, tests/fixtures/customer.json, tests/test_customer_client.py
This PR adds support for shipping address that will be used in tax integrations.
=> feat(customers): add support for customer shipping address

lago_python_client/client.py, lago_python_client/models/gross_revenue.py, lago_python_client/models/overdue_balance.py, lago_python_client/overdue_balances/clients.py, tests/fixtures/overdue_balance_index.json, tests/test_gross_revenue_client.py, tests/test_overdue_balance_client.py
👉 https://getlago.canny.io/feature-requests/p/regroup-invoices-to-generate-one-payment-intent
We want to be able to group invoices to generate one payment.
Today we don't track payment terms and do not mention whether a payment or an invoice is overdue.
The goal of this PR is to add an analytics endpoint for fetching overdue balances per month and per currency at the customer or organization level.
=> feat(analytics): Add overdue balance endpoint

lago_python_client/version.py
As announced a few months ago, this release updates the event ingestion process and removes deprecated API fields.
Changes include:
The new dimension system based on filters is already available. It allows users to create billable metrics with more than two dimensions, and makes it easier to create charges based on custom event properties. The former dimension system based on groups is now permanently removed from the Lago API ([see all changes](https://docs.getlago.com/guide/migration/migration-to-v1.2.0#1-transition-from-group-to-filters)).
Events that only include external_customer_id will no longer be taken into account when aggregating usage ([learn more](https://docs.getlago.com/guide/migration/migration-to-v1.2.0#2-mandatory-external-subscription-id-field-in-event-payloads)). This …
=> misc(version): Bump to v1.7.0

lago_python_client/client.py, lago_python_client/models/payment_request.py, lago_python_client/payment_requests/clients.py, tests/fixtures/payment_request_index.json, tests/test_payment_request_client.py
See https://github.com/getlago/lago-api/pull/2420
=> feat(dunning): Add payment requests endpoint (find_all)

lago_python_client/models/fee.py
For some customers some amounts are not enough precise as Lago convert fees to `amount_cent`.
Add precise amounts to fee model.
=> feat(precise-amounts): Add precise amounts to fee model

lago_python_client/models/__init__.py, lago_python_client/models/lifetime_usage.py, lago_python_client/subscriptions/clients.py, tests/fixtures/lifetime_usage.json, tests/fixtures/update_lifetime_usage.json, tests/test_subscription_client.py
AI companies want their users to pay before the end of a period if usage skyrockets. The problem being that self-serve companies can overuse their API without paying, triggering lots of costs on their side.
Adds 2 methods `lifetime_usage` and `update_lifetime_usage` to Subscription client.
=> feat(ProgressiveBilling) - add `lifetime_usage` and `update_lifetime_usage` to Subscription

lago_python_client/exceptions.py, tests/fixtures/event_unprocessable_entity.json, tests/test_event_client.py
This PR fixes https://github.com/getlago/lago-python-client/issues/266
It makes sure that `LagoApiError` shows a comprehensible message in the output. It will render the API response, allowing user to quickly understand the source of the error.
```
lago_python_client.exceptions.LagoApiError
```
```
lago_python_client.exceptions.LagoApiError: {'status': 422, 'error': 'Unprocessable Entity', 'code': 'validation_errors', 'error_details': {'transaction_id': ['value_already_exist']}}
```
=> fix: Improve LagoApiError details

lago_python_client/models/event.py, tests/fixtures/event.json
AI, CPaaS and Fintech customers can apply a price to a unit that fluctuates over time. Currently Lago does not support this usecase.
This PR is related to https://github.com/getlago/lago-api/pull/2610.
It documents the new `precise_total_amount_cents` in input and result payloads on `POST /api/v1/events` and `POST /api/v1/batch_events`
=> feat(DynamicPricing): Expose Event#precise_total_amount_cents

lago_python_client/models/billable_metric.py, lago_python_client/models/plan.py, lago_python_client/models/tax.py, tests/fixtures/billable_metric.json, tests/fixtures/billable_metric_index.json, tests/fixtures/plan.json, tests/fixtures/plan_index.json, tests/fixtures/tax.json, tests/fixtures/tax_index.json
The API response are returning a lot of counters. Since the exposed resources can be linked to a lot of objects and can be called a lot, these counters are posing a scalability problem and are slowing down the global performance of the API.
To remediate the situation the decision was made to remove all these fields.
This PR removes the following fields:
- BillableMetric
-  active_subscriptions_count
- draft_invoices_count
- plans_count
- Plan
- active_subscriptions_count
- draft_invoices_count
- Tax
- add_ons_count
- charges_count
- customers_count
- plans_count
=> misc: Remove *_count fields

lago_python_client/customers/clients.py, lago_python_client/gross_revenues/clients.py, lago_python_client/invoice_collections/clients.py, lago_python_client/invoiced_usages/clients.py, lago_python_client/mixins.py, lago_python_client/mrrs/clients.py, lago_python_client/overdue_balances/clients.py, lago_python_client/services/request.py, lago_python_client/wallets/clients.py, tests/test_request_services.py
Allows passing multiple list param values such as with `status[]` in list subscriptions.
=> feat: allow passing tuples and list values as query params

lago_python_client/models/__init__.py, lago_python_client/models/billing_period.py, lago_python_client/models/invoice.py, tests/fixtures/invoice.json
Related to https://github.com/getlago/lago-api/pull/3064
=> feat: Expose billing periods with invoice object

lago_python_client/customers/clients.py, tests/test_customer_client.py
Updated the current_usage method to accept an optional apply_taxes parameter, defaulting to True. This parameter is included in the query string as a lowercase string ("true" or "false").
=> feat: add apply taxes params to current usage

lago_python_client/models/__init__.py, lago_python_client/models/wallet.py, tests/fixtures/wallet.json, tests/fixtures/wallet_index.json, tests/test_wallet_client.py
This PR adds support for applies_to attribute that handles wallet limitations
=> feat(wallet-limitations): add support for wallet fee type limitation

README.md, lago_python_client/models/subscription.py, setup.cfg, tests/fixtures/subscription.json, tests/test_subscription_client.py
This also updates the `setup.cfg` to include `ruff` as a dependency and add a "Linting" section in the README.
=> feat(subscription): Add `on_termination_credit_note` field to subscription

lago_python_client/models/wallet.py, tests/fixtures/wallet.json, tests/fixtures/wallet_index.json, tests/test_wallet_client.py
This PR adds support for limiting wallet consumption on specific billable metric types.
New attribute called `billable_metric_codes` is added inside `applies_to` object in both request and response.
=> feat (wallets): add support for wallet bm limitation

lago_python_client/models/__init__.py, lago_python_client/models/billing_entity.py, lago_python_client/models/customer.py, lago_python_client/models/invoice_custom_section.py, tests/fixtures/billing_entity.json, tests/fixtures/billing_entity_index.json, tests/fixtures/customer.json, tests/test_billing_entity_client.py, tests/test_customer_client.py
enable invoice custom sections for billing entities.
=> feat(multientities): Support for invoice custom sections for billing entities

lago_python_client/models/wallet.py, tests/fixtures/wallet.json, tests/test_wallet_client.py
👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4282.
This adds a `transaction_name` to the wallet transaction recurring rule types that are then used to populate the name of the triggered wallet transactions.
=> feat(wallet-transaction): Add `transaction_name` to wallet transaction rules

lago_python_client/models/customer_projected_usage.py, lago_python_client/models/customer_usage.py
This pull request updates the type annotations for the `grouped_by` field in two usage-related model classes to allow for `None` values in the dictionary values. This change ensures that the models can represent cases where some grouping keys may not have a value.
Model updates for grouping support:
* Updated the `grouped_by` field in the `GroupedUsage` class in `customer_usage.py` to use `Dict[str, str | None]`, allowing grouping values to be `None`.
* Updated the `grouped_by` field in the `ProjectedGroupedUsage` class in `customer_projected_usage.py` to use `Dict[str, str | None]`, allowing grouping values to be `None`.
=> fix(models): Update `grouped_by` type to allow None in ProjectedGroupedUsage and GroupedUsage classes
